version: '3'

services:
  oop-core:
    image: "openinterop/oop-core:latest"
    ports:
      - "9001:9001"
    env_file:
      - all.env
    #depends_on:
    #  - database
    volumes:
      - gem_cache:/gems
      - './config/database.yml:/app/config/database.yml'
      - './config/storage.yml:/app/config/storage.yml'
      - './config/secrets.yml:/app/config/secrets.yml'

  oop-gateway:
    image: "openinterop/oop-gateway:latest"
    ports:
      - "3000:3000"
    env_file:
      - all.env

  oop-authenticator:
    image: "openinterop/oop-authenticator:latest"
    env_file:
      - all.env
    depends_on:
      - oop-core

  oop-tempr:
    image: "openinterop/oop-tempr:latest"
    env_file:
      - all.env

  oop-renderer:
    image: "openinterop/oop-renderer:latest"
    env_file:
      - all.env

  oop-endpoints-http:
    image: "openinterop/oop-endpoints-http:latest"
    env_file:
      - all.env

  oop-relay:
    image: "openinterop/oop-relay:latest"
    env_file:
      - all.env

  #database:
  #  image: postgres
  #  env_file:
  #    - all.env
  #  volumes:
  #    - db_data:/var/lib/postgresql/data

volumes:
  #db_data:
  gem_cache:
